name: CD

on: [ release ]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up maven
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'
                  server-id: sparky-releases
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Publish package
              run: mvn --batch-mode deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.SPARKY_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.SPARKY_TOKEN }}
